Weather APP
Emmanuelaaron/weatherApp pull request #1
Opened 2021-05-15 03:56 UTC by Emmanuelaaron

## I have made a JavaScript implementation of fetching data from a weather API and displaying it in the browser
### Tools and Techs used
- JavaScript
- HTML and CSS
- Bootstrap
- Eslint

2021-05-18 07:12 UTC, whiz25 requested changes
## Changes Required 🙏🏿 🙏🏿 🙏🏿 
Good job on this PR.
### Nice work 🌵 🌵 🌵 
- Use of `promises`
- Logic divide into modules
- Can search for weather for a specific location
### Changes to make 🙅🏿 🙅🏿 🙅🏿 
- Add a toggle button to flip the temperature value between Celsius and Fahrenheit
- The background image should change based on the temperature. For example, I should see the sun when it's sunny, etc
- Separate JS logic from DOM manipulation logic
- Check comments for suggestions


### Martin Afani
#### Slack: whiz25

2021-05-18 07:12 UTC, whiz25 commented on src/functions/apifunc.js
> +    });
- Wrap this block in a `try/catch` for error handling
- Separate JS logic from DOM manipulation. This file should only contain JS code.

2021-05-18 07:12 UTC, whiz25 commented on src/components/inputForm.js
> +  });
- DOM manipulation logic should live in the `dom` folder.

2021-05-18 07:12 UTC, whiz25 commented on src/components/weatherData.js
> +  return fullBodyContent;
- Move any DOM logic to the `dom` folder

2021-05-18 07:12 UTC, whiz25 commented on README.md
> +- Navigate to this project on your machine
- Give explicit commands to be run

2021-05-21 13:15 UTC, oloomoses requested changes
### Changes Required :recycle: 
Hello @Emmanuelaaron,

**You have done a great job implementing the changes suggested by @whiz25. :muscle:**
However, some issues have not been handled properly.

### To improve
- [ ] Kindly Add a button to toggle the temperature value between Celsius and Fahrenheit. You can either use a radion or toggle button
- [ ] The app should change its appearance based on the received data ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/weather_app/appearance_requirement.png))

**Kindly make the above changes and ask for another review**

Feel free to reach me on slack or leave a comment while mentioning me and I will  be happy to respond

_Slack: Oloo Moses_

2021-06-03 20:38 UTC, MkrtichSargsyan approved these changes
## _Status:_ Approved  :hamster: :rocket:
Hello :wave:.

Awesome job on this project.:rocket: You have completed all the requested changes from the previous code reviewer.

You can go ahead and merge this branch to the base branch of this repo.
Good luck in your future projects and happy coding :relaxed:

> ps: . If you have any questions about my review or need help, you can message me on slack ( @mkrtichsargsyan )

2021-06-04 05:11 UTC, merged